image: docker-hosted.snap-ci.ovh/snap-installer:unix-latest

variables:
  TEST_DATA_LIST: singleTestData.txt
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  # $DOCKER_AUTH_CONFIG should have been setup as projet variable
  SCOPE: s3tbx
  REPORT_DIR: "${CI_PROJECT_DIR}/result"
  TEST_DATA_DIR: "${CI_PROJECT_DIR}/testData"
  MAVEN_CLI_OPTS: >-
    --no-transfer-progress
    --batch-mode
    --errors
    --fail-at-end
    --show-version
    -DinstallAtEnd=false
    -DdeployAtEnd=false
  S3_ARGS: --endpoint-url $S3_ENDPOINT --region sbg --no-progress

cache:
  - key: ${CI_CI_COMMIT_BRANCH}
    paths:
      - "${CI_PROJECT_DIR}/.m2"
      - ".cache/pip"
      - "/home/snap/.local/bin"
      - "${CI_PROJECT_DIR}/**/target"

stages:
  - prepare
  - test
  - clean

prepare:
  stage: prepare
  tags:
    - kube
  script:
    # Clean old report
    - rm -rf $REPORT_DIR
    - mkdir -p $TEST_DATA_DIR/$SCOPE $REPORT_DIR/report/output
    # build project
    - mvn $MAVEN_CLI_OPTS package install
    - pip3 install -r $CI_PROJECT_DIR/requirements.txt
    - pip3 install awscli
  artifacts:
    untracked: true
    when: always
    expire_in: "10 days"
    paths:
      - "${REPORT_DIR}"

.prepare:
  cache:
    - key: ${CI_CI_COMMIT_BRANCH}
      paths:
      - "${CI_PROJECT_DIR}/.m2"
      - ".cache/pip"
      - "/home/snap/.local/bin"
      - "${CI_PROJECT_DIR}/**/target"
    - key: ${CI_COMMIT_BRANCH}-$SCOPE-$CI_NODE_INDEX
      paths:
        - ${TEST_DATA_DIR}/$(echo sed "${CI_NODE_INDEX}q;d" $REPORT_DIR/JSONTestFiles.txt)
  before_script:
    # build project
    # - mvn $MAVEN_CLI_OPTS package install
    # - pip3 install -r $CI_PROJECT_DIR/requirements.txt
    # - pip3 install awscli
    # Produce a list of tests to run
    - python3 $CI_PROJECT_DIR/pygpt/filter_json.py gpt-tests-resources/tests $SCOPE $REPORT_DIR
    - cat $REPORT_DIR/testData.txt
    # Get test data for single test file
    - |
      export test=$(sed "${CI_NODE_INDEX}q;d" $REPORT_DIR/JSONTestFiles.txt)
      python3 $CI_PROJECT_DIR/pygpt/get_test_data_list.py $test $REPORT_DIR
    # Download test data
    - |
      export line=$(sed "${CI_NODE_INDEX}q;d" $REPORT_DIR/$TEST_DATA_LIST)
      if [ ! -a "$TEST_DATA_DIR/$line" ] && [ ! -d "$TEST_DATA_DIR/$line" ]; then
        if [[ "$line" =~ (.xml|.XML|.JP2|.zip|.ZIP|.tgz|.NTF|.dim|.DIMA|.h5|.txt|.tif|_OC)$ ]]; then
          echo "Download file ${line}"
          ~/.local/bin/aws s3 cp "s3://$S3_BUCKET/testData/$line" "$TEST_DATA_DIR/$line" $S3_ARGS
        else
          echo "Download directory ${line}"
          ~/.local/bin/aws s3 cp "s3://$S3_BUCKET/testData/$line" "$TEST_DATA_DIR/$line" $S3_ARGS --recursive
        fi
      else
        echo "$line exists: skip download"
      fi


.test:
  tags:
    - kube
  script:
    - echo "Running $(sed "${CI_NODE_INDEX}q;d" ${REPORT_DIR}/JSONTestFiles.txt)"
    - |
      export FILE=$(sed "${CI_NODE_INDEX}q;d" $REPORT_DIR/JSONTestFiles.txt)
      python3 pygpt/snap_gpt_test.py java "${JAVA_OPTIONS} -cp ${CI_PROJECT_DIR}/gpt-tests-executer/target/TestOutput.jar" \
        org.esa.snap.test.TestOutput $PROPERTIES_PATH $SCOPE $FILE $REPORT_DIR true
  after_script:
    # Copy assets for report generation
    - cp -R $REPORT_DIR/report/output/* pygpt/statics/* $REPORT_DIR/report
    - echo "Generate report"
    - python3 pygpt/report_utils.py pygpt/templates $REPORT_DIR/report $SCOPE snap:master
  needs:
    - "prepare"
  artifacts:
    untracked: true
    when: always
    expire_in: "10 days"
    paths:
      - "${REPORT_DIR}/report"

test_s3tbx:
  stage: test
  rules:
    - if: $SCOPE == 's3tbx'
      when: always
    - when: never
  parallel: 22
  extends: [.prepare,.test]

test_s2tbx:
  stage: test
  rules:
    - if: $SCOPE == 's2tbx'
      when: always
    - when: never
  parallel: 100
  extends: [.prepare,.test]

test_s1tbx:
  stage: test
  rules:
    - if: $SCOPE == 's1tbx'
      when: always
    - when: never
  parallel: 34
  extends: [.prepare,.test]

test_snap:
  stage: test
  rules:
    - if: $SCOPE == 'snap'
      when: always
    - when: never
  parallel: 26
  extends: [.prepare,.test]

test_all:
  stage: test
  tags:
    - kube
  rules:
    - if: $SCOPE == 'all'
  parallel:
    matrix:
      - SCOPE: s1tbx
        CI_NODE_INDEX: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,26,27,28,29,30,31,32,33,34]
      - SCOPE: s2tbx
        CI_NODE_INDEX: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100]
      - SCOPE: s3tbx
        CI_NODE_INDEX: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22]
      - SCOPE: snap
        CI_NODE_INDEX: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,26]
  extends:
    - test_s1tbx
    - test_s2tbx
    - test_s3tbx
    - test_snap

test_windows:
  stage: test
  tags:
    - windows
  image: docker-hosted.snap-ci.ovh/snap/snap-installer:win-latest
  variables:
    SCOPE: daily
    SNAP_DIR: /c/users/snap
    TAG: master
    PROPERTIES_PATH: $CI_PROJECT_DIR/snap.conf
  extends: .prepare
  script:
    - ${CI_PROJECT_DIR}/run_tests.sh $SNAP_DIR $SCOPE $REPORT_DIR $TAG

test_mac:
  stage: test
  image: macos-12-xcode-14
  variables:
    SCOPE: daily
    SNAP_DIR: /opt/snap
    TAG: master
    PROPERTIES_PATH: $CI_PROJECT_DIR/snap.conf
  extends: .prepare
  script:
    - ${CI_PROJECT_DIR}/run_tests.sh $SNAP_DIR $SCOPE $REPORT_DIR $TAG

clean:
  stage: clean
  tags:
    - kube
  script:
    - echo "Clean up"
    - rm -rf $REPORT_DIR/report/output